// Auto-generated from real OLX listings via /tmp/regen_mock.py.
// Replaced in chunk 2 by hot_deals_{zone}.json fetched from the
// latest-data GitHub Release at request time.

export const MOCK_DEALS = {
  "norte": [
    {
      "olx_id": "JpNY5",
      "url": "https://www.olx.pt/d/anuncio/kia-ceed-2010-diesel-IDJpNY5.html?search_reason=search%7Corganic",
      "title": "Kia Ceed 2010 Diesel",
      "brand": "Kia",
      "model": "Ceed",
      "year": 2010,
      "mileage_km": 230000,
      "fuel_type": "diesel",
      "transmission": "manual",
      "price_eur": 2600,
      "fair_low": 3335,
      "fair_median": 3586,
      "fair_high": 3873,
      "discount_pct": 0.275,
      "est_profit_eur": 486,
      "first_seen_at": "2026-05-24T13:31:03.220846Z",
      "days_on_market": 0,
      "district": "Porto",
      "city": "São Mamede De Infesta E Senhora Da Hora",
      "seller_type": "Particular",
      "damage_severity": 1,
      "photo_damage_p": 0.8238,
      "photo_damage_flagged": false,
      "photo_urls": [
        "https://ireland.apollo.olxcdn.com:443/v1/files/tw25kjx76mjg1-PT/image;s=572x1020"
      ],
      "description_excerpt": "Vendo Kia Ceed 2010 turbo Diesel em bom estado. Carrinha completa, rodas de liga, retrovisores elétricos, limpador de parabrisa automáticos etc"
    },
    {
      "olx_id": "JpO4H",
      "url": "https://www.olx.pt/d/anuncio/ford-focus-1-5tdci-nacional-muitos-extras-IDJpO4H.html?search_reason=search%7Corganic",
      "title": "Ford Focus 1.5TDCi Nacional Muitos Extras",
      "brand": "Ford",
      "model": "Focus",
      "year": 2015,
      "mileage_km": 299000,
      "fuel_type": "diesel",
      "transmission": "manual",
      "price_eur": 6000,
      "fair_low": 6683,
      "fair_median": 7186,
      "fair_high": 7761,
      "discount_pct": 0.165,
      "est_profit_eur": 686,
      "first_seen_at": "2026-05-24T13:30:47.539563Z",
      "days_on_market": 0,
      "district": "Braga",
      "city": "Lomar E Arcos",
      "seller_type": "Particular",
      "damage_severity": 1,
      "photo_damage_p": 0.0178,
      "photo_damage_flagged": false,
      "photo_urls": [
        "https://ireland.apollo.olxcdn.com:443/v1/files/p2bleprzjg262-PT/image;s=1000x667"
      ],
      "description_excerpt": "Ford Focus 1.5TDCi FULL-EXTRAS Nacional - 299.000kms; - 1499cc | 120cv; - Caixa Manual; - Jun/2015; - Diesel; - Correia de distribuição e Revisão feitos a 30.000kms Quilómetros maioritariamente feitos em auto-estrada - 2 Chaves c/Comando; - Excelente Desempenho e Consumo; -..."
    },
    {
      "olx_id": "JpOrt",
      "url": "https://www.olx.pt/d/anuncio/renault-megane-1-5-dci-verso-dynamique-IDJpOrt.html?search_reason=search%7Corganic",
      "title": "Renault Megane 1.5 Dci Versão Dynamique",
      "brand": "Renault",
      "model": "Mégane Break",
      "year": 2012,
      "mileage_km": 212000,
      "fuel_type": "diesel",
      "transmission": "manual",
      "price_eur": 5500,
      "fair_low": 6475,
      "fair_median": 6962,
      "fair_high": 7519,
      "discount_pct": 0.21,
      "est_profit_eur": 962,
      "first_seen_at": "2026-05-24T13:29:55.831431Z",
      "days_on_market": 0,
      "district": "Porto",
      "city": "Ramalde",
      "seller_type": "Particular",
      "damage_severity": 0,
      "photo_damage_p": 0.004,
      "photo_damage_flagged": false,
      "photo_urls": [
        "https://ireland.apollo.olxcdn.com:443/v1/files/3afyj9pqqklx-PT/image;s=1000x750"
      ],
      "description_excerpt": "Vendo Renault Megane 1.5 Dci versão de equipamento Dynamic. Viatura com 210.000km (kms reais) comprada na Renault Boavista com 43.000km (com fatura a comprovar) Todas as revisões efectuadas e com distribuição mudada. Duas chaves e todos os manuais. Consumos de 6l/100 Ano de..."
    },
    {
      "olx_id": "JgFLL",
      "url": "https://www.olx.pt/d/anuncio/venda-bmw-116-automatico-IDJgFLL.html?search_reason=search%7Corganic",
      "title": "Venda Bmw 116 Automatico",
      "brand": "BMW",
      "model": "116",
      "year": 2017,
      "mileage_km": 93300,
      "fuel_type": "diesel",
      "transmission": "automática",
      "price_eur": 17900,
      "fair_low": 20809,
      "fair_median": 22375,
      "fair_high": 24165,
      "discount_pct": 0.2,
      "est_profit_eur": 3975,
      "first_seen_at": "2026-05-24T13:29:32.787086Z",
      "days_on_market": 0,
      "district": "Aveiro",
      "city": "Glória E Vera Cruz",
      "seller_type": "Particular",
      "damage_severity": 0,
      "photo_damage_p": 0.0048,
      "photo_damage_flagged": false,
      "photo_urls": [
        "https://ireland.apollo.olxcdn.com:443/v1/files/ox9993gsqueq3-PT/image;s=1000x1000"
      ],
      "description_excerpt": "Veículo irrepreensível com poucos Km, óptimos consumos mecânica fiável, com possibilidade de financiamento. Um único proprietário, assistido na marca."
    },
    {
      "olx_id": "JdND4",
      "url": "https://www.olx.pt/d/anuncio/hyundai-tucson-4wd-IDJdND4.html?search_reason=search%7Corganic",
      "title": "Hyundai tucson 4wd",
      "brand": "Hyundai",
      "model": "Tucson",
      "year": 2018,
      "mileage_km": 80000,
      "fuel_type": "diesel",
      "transmission": "automática",
      "price_eur": 18000,
      "fair_low": 23678,
      "fair_median": 25460,
      "fair_high": 27497,
      "discount_pct": 0.293,
      "est_profit_eur": 6960,
      "first_seen_at": "2026-05-24T13:29:10.197324Z",
      "days_on_market": 0,
      "district": "Porto",
      "city": "Mancelos",
      "seller_type": "Particular",
      "damage_severity": 1,
      "photo_damage_p": 0.0166,
      "photo_damage_flagged": false,
      "photo_urls": [
        "https://ireland.apollo.olxcdn.com:443/v1/files/j76wr16j8z17-PT/image;s=756x1008"
      ],
      "description_excerpt": "Hyundai Tucson 2.0 CRDi – 184cv ​Destaque Principal: Excelente oportunidade para quem procura um SUV robusto, potente e fiável. Versão de 184cv (2.0L), com uma condução superior e muito equipamento. ​Características Principais: ​Ano: Junho de 2018 ​Quilometragem: 80.000 km..."
    }
  ],
  "centro": [
    {
      "olx_id": "JpOBq",
      "url": "https://www.olx.pt/d/anuncio/renault-zoe-52kw-IDJpOBq.html?search_reason=search%7Corganic",
      "title": "RENAULT ZOE 52KW",
      "brand": "Renault",
      "model": "Zoe",
      "year": 2021,
      "mileage_km": 95291,
      "fuel_type": "eléctrico",
      "transmission": "automática",
      "price_eur": 13900,
      "fair_low": 18004,
      "fair_median": 19359,
      "fair_high": 20908,
      "discount_pct": 0.282,
      "est_profit_eur": 4959,
      "first_seen_at": "2026-05-24T13:31:39.753263Z",
      "days_on_market": 0,
      "district": "Coimbra",
      "city": "Ázere E Covelo",
      "seller_type": "Particular",
      "damage_severity": 1,
      "photo_damage_p": 0.0936,
      "photo_damage_flagged": false,
      "photo_urls": [
        "https://ireland.apollo.olxcdn.com:443/v1/files/r9fh3vpln14r1-PT/image;s=4284x5712"
      ],
      "description_excerpt": "Renault zoe 52Kw com bateria própria. Bateria com garantia ate 2029. Bancos aquecidos. Volante aquecido. Espelhos rebatíveis. Mudança de máximos automático. Em muito bom estado."
    },
    {
      "olx_id": "IsYvG",
      "url": "https://www.olx.pt/d/anuncio/fiat-500c-1-2-2013-IDIsYvG.html?search_reason=search%7Corganic",
      "title": "Fiat 500C 1.2 2013",
      "brand": "Fiat",
      "model": "500C",
      "year": 2013,
      "mileage_km": 100000,
      "fuel_type": "gasolina",
      "transmission": "manual",
      "price_eur": 7500,
      "fair_low": 10273,
      "fair_median": 11046,
      "fair_high": 11930,
      "discount_pct": 0.321,
      "est_profit_eur": 3046,
      "first_seen_at": "2026-05-24T13:31:15.116588Z",
      "days_on_market": 0,
      "district": "Santarém",
      "city": "Samora Correia",
      "seller_type": "Particular",
      "damage_severity": 1,
      "photo_damage_p": 0.0024,
      "photo_damage_flagged": false,
      "photo_urls": [
        "https://ireland.apollo.olxcdn.com:443/v1/files/jaqyicuu885m-PT/image;s=1041x886"
      ],
      "description_excerpt": "⁃ Ano: 12/2013 ⁃ Quilometragem: 100000 ⁃ Motor: 1.2L ⁃ Cor: Vermelho Maçã Doce Especial ⁃ uma tonalidade rara e atraente ⁃ Condução sem esforço na cidade ou na rodovia ⁃ Interior: Elegante combinação bege e vermelho ⁃ confortável e elegante ⁃ Conversível: Desfrute do sol e do ar..."
    },
    {
      "olx_id": "JpOzW",
      "url": "https://www.olx.pt/d/anuncio/ford-fiesta-1-4-tdci-titanium-2011-IDJpOzW.html?search_reason=search%7Corganic",
      "title": "Ford Fiesta 1.4 TDCi Titanium 2011",
      "brand": "Ford",
      "model": "Fiesta",
      "year": 2011,
      "mileage_km": 210000,
      "fuel_type": "diesel",
      "transmission": "manual",
      "price_eur": 5500,
      "fair_low": 6208,
      "fair_median": 6675,
      "fair_high": 7209,
      "discount_pct": 0.176,
      "est_profit_eur": 675,
      "first_seen_at": "2026-05-24T13:29:57.996339Z",
      "days_on_market": 0,
      "district": "Santarém",
      "city": "Meia Via",
      "seller_type": "Particular",
      "damage_severity": 1,
      "photo_damage_p": 0.0042,
      "photo_damage_flagged": false,
      "photo_urls": [
        "https://ireland.apollo.olxcdn.com:443/v1/files/b3xb6cgg3zd33-PT/image;s=750x1000"
      ],
      "description_excerpt": "Ford Fiesta 1.4 TDCi Titanium 2011 Vendo Ford Fiesta VI Mk6 1.4 TDCi, ano 2011, cor preta, com 200.000 km. Viatura em bom estado geral, muito económica e fiável, ideal para utilização diária ou viagens. Motor 1.4 TDCi conhecido pelos baixos consumos e boa durabilidade. Faróis..."
    },
    {
      "olx_id": "JpNUB",
      "url": "https://www.olx.pt/d/anuncio/peugeot-308-sw-allure-IDJpNUB.html?search_reason=search%7Corganic",
      "title": "Peugeot 308 SW Allure",
      "brand": "Peugeot",
      "model": "308",
      "year": 2015,
      "mileage_km": 283000,
      "fuel_type": "diesel",
      "transmission": "manual",
      "price_eur": 6999,
      "fair_low": 8520,
      "fair_median": 9161,
      "fair_high": 9894,
      "discount_pct": 0.236,
      "est_profit_eur": 1662,
      "first_seen_at": "2026-05-24T09:56:18.441891Z",
      "days_on_market": 0,
      "district": "Viseu",
      "city": "São Pedro Do Sul, Várzea E Baiões",
      "seller_type": "Particular",
      "damage_severity": 0,
      "photo_damage_p": 0.0244,
      "photo_damage_flagged": false,
      "photo_urls": [
        "https://ireland.apollo.olxcdn.com:443/v1/files/zyxsuj0aau2z-PT/image;s=750x1000"
      ],
      "description_excerpt": "Peugeot 308 II SW BlueHDI 120cv • 1.6cc BlueHDI - 120cv - GASÓLEO • Caixa manual - 6 velocidades • 02/2015 com IPO válida • 283.000km •Versão Allure, a destacar: -Teto Panorâmico -Computador de bordo -Volante multifuncional -Cruise control adaptativo + Limitador de velocidade -..."
    },
    {
      "olx_id": "JpLgu",
      "url": "https://www.olx.pt/d/anuncio/vendo-ford-focus-IDJpLgu.html?search_reason=search%7Corganic",
      "title": "Vendo Ford Focus",
      "brand": "Ford",
      "model": "Focus",
      "year": 2017,
      "mileage_km": 168000,
      "fuel_type": "gasolina",
      "transmission": "manual",
      "price_eur": 9000,
      "fair_low": 10024,
      "fair_median": 10778,
      "fair_high": 11640,
      "discount_pct": 0.165,
      "est_profit_eur": 1278,
      "first_seen_at": "2026-05-24T07:41:07.176928Z",
      "days_on_market": 0,
      "district": "Guarda",
      "city": "Guarda",
      "seller_type": "Particular",
      "damage_severity": 1,
      "photo_damage_p": 0.2562,
      "photo_damage_flagged": false,
      "photo_urls": [
        "https://ireland.apollo.olxcdn.com:443/v1/files/fqbmnvs8kmqt2-PT/image;s=768x1020"
      ],
      "description_excerpt": "Ano 2017 Em muito bom estado Único proprietário"
    }
  ],
  "sul": [
    {
      "olx_id": "JgwZi",
      "url": "https://www.olx.pt/d/anuncio/mitsubishi-space-star-IDJgwZi.html?search_reason=search%7Corganic",
      "title": "Mitsubishi space star",
      "brand": "Mitsubishi",
      "model": "Space Star",
      "year": 2021,
      "mileage_km": 92112,
      "fuel_type": "gasolina",
      "transmission": "manual",
      "price_eur": 8500,
      "fair_low": 9869,
      "fair_median": 10612,
      "fair_high": 11461,
      "discount_pct": 0.199,
      "est_profit_eur": 1612,
      "first_seen_at": "2026-05-24T13:30:18.590393Z",
      "days_on_market": 0,
      "district": "Setúbal",
      "city": "Montijo E Afonsoeiro",
      "seller_type": "Particular",
      "damage_severity": 1,
      "photo_damage_p": 0.3441,
      "photo_damage_flagged": false,
      "photo_urls": [
        "https://ireland.apollo.olxcdn.com:443/v1/files/a4it8ah9blsj1-PT/image;s=750x1000"
      ],
      "description_excerpt": "Para venda,  mitsubishi space star, citadino ideal para quem quer um carro pequeno e económico"
    },
    {
      "olx_id": "JpOeh",
      "url": "https://www.olx.pt/d/anuncio/citroen-ds3-1-6-hdi-IDJpOeh.html?search_reason=search%7Corganic",
      "title": "Citroen ds3 1.6 hdi",
      "brand": "Citroën",
      "model": "DS3",
      "year": 2015,
      "mileage_km": 228000,
      "fuel_type": "diesel",
      "transmission": "manual",
      "price_eur": 7250,
      "fair_low": 9002,
      "fair_median": 9680,
      "fair_high": 10454,
      "discount_pct": 0.251,
      "est_profit_eur": 1930,
      "first_seen_at": "2026-05-24T13:28:56.447580Z",
      "days_on_market": 0,
      "district": "Lisboa",
      "city": "Alenquer (Santo Estêvão E Triana)",
      "seller_type": "Particular",
      "damage_severity": 1,
      "photo_damage_p": 0.9871,
      "photo_damage_flagged": true,
      "photo_urls": [
        "https://ireland.apollo.olxcdn.com:443/v1/files/r47a2h5fambk2-PT/image;s=1600x1200"
      ],
      "description_excerpt": "Vendo citroen ds3 1.6 hdi . Carro em muito bom estado ,sem nada a fazer. Inspeção feita no mês 4 e tudo certo . Carro com revisão feita ."
    },
    {
      "olx_id": "JpOvr",
      "url": "https://www.olx.pt/d/anuncio/audi-a1-sportback-1-6-tdi-90cv-5-portas-econmico-ultra-fivel-em-ptimo-estado-IDJpOvr.html?search_reason=search%7Corganic",
      "title": "Audi A1 Sportback 1.6 TDI 90cv (5 Portas) – Económico, Ultra-Fiável em Óptimo Estado",
      "brand": "Audi",
      "model": "A1 Sportback",
      "year": 2014,
      "mileage_km": 124500,
      "fuel_type": "diesel",
      "transmission": "manual",
      "price_eur": 11990,
      "fair_low": 13354,
      "fair_median": 14359,
      "fair_high": 15508,
      "discount_pct": 0.165,
      "est_profit_eur": 1869,
      "first_seen_at": "2026-05-24T13:28:49.203234Z",
      "days_on_market": 0,
      "district": "Lisboa",
      "city": "Falagueira-Venda Nova",
      "seller_type": "Particular",
      "damage_severity": 0,
      "photo_damage_p": 0.4739,
      "photo_damage_flagged": false,
      "photo_urls": [
        "https://ireland.apollo.olxcdn.com:443/v1/files/d4bmcejfgfyz-PT/image;s=1500x2000"
      ],
      "description_excerpt": "Vendo Audi A1 Sportback de 5 portas em estado absolutamente impecável. Passámos a ter carro de empresa e deixámos de necessitar deste 2º carro. Trata-se da versão Ambition, equipada com o fiável motor 1.6 TDI de 90 cv (Código CAYB), conhecido pelos seus consumos extraordinários..."
    },
    {
      "olx_id": "JpbtM",
      "url": "https://www.olx.pt/d/anuncio/range-rover-evoque-IDJpbtM.html?search_reason=search%7Corganic",
      "title": "Range Rover Evoque",
      "brand": "Land Rover",
      "model": "Evoque",
      "year": 2016,
      "mileage_km": 160000,
      "fuel_type": "diesel",
      "transmission": "manual",
      "price_eur": 16500,
      "fair_low": 19085,
      "fair_median": 20522,
      "fair_high": 22164,
      "discount_pct": 0.196,
      "est_profit_eur": 3522,
      "first_seen_at": "2026-05-24T13:28:03.676503Z",
      "days_on_market": 0,
      "district": "Évora",
      "city": "Évora (São Mamede, Sé, São Pedro E Santo Antão)",
      "seller_type": "Particular",
      "damage_severity": 1,
      "photo_damage_p": 0.2584,
      "photo_damage_flagged": false,
      "photo_urls": [
        "https://ireland.apollo.olxcdn.com:443/v1/files/8sw3nohmt8v21-PT/image;s=576x1024"
      ],
      "description_excerpt": "Vendo Range Rover Evoque , Ano 2016 , NACIONAL ,muito Bonito de Pintura, Motor a trabalhar na Perfeição com Revisões todas feitas!! Inspeção valida até Janeiro 2027 Excelente Oportunidade de Negócio!!! Aceito Retomas ou Trocas!! Possibilidade de fazer Financiamento Crédito sem..."
    },
    {
      "olx_id": "JpOze",
      "url": "https://www.olx.pt/d/anuncio/jaguar-e-pace-com-motor-novo-IDJpOze.html?search_reason=search%7Corganic",
      "title": "Jaguar E-Pace com motor novo!!!",
      "brand": "Jaguar",
      "model": "E-Pace",
      "year": 2018,
      "mileage_km": 160000,
      "fuel_type": "gasolina",
      "transmission": "manual",
      "price_eur": 16000,
      "fair_low": 20581,
      "fair_median": 22130,
      "fair_high": 23900,
      "discount_pct": 0.277,
      "est_profit_eur": 5630,
      "first_seen_at": "2026-05-24T13:27:29.215673Z",
      "days_on_market": 0,
      "district": "Setúbal",
      "city": "Caparica E Trafaria",
      "seller_type": "Particular",
      "damage_severity": 0,
      "photo_damage_p": 0.7845,
      "photo_damage_flagged": false,
      "photo_urls": [
        "https://ireland.apollo.olxcdn.com:443/v1/files/xjalhkf6vhdp3-PT/image;s=1125x816"
      ],
      "description_excerpt": "Jaguar E-Pace 2.0 Dynamic em excelente estado geral, combinando conforto, elegância e uma condução premium. A viatura recebeu recentemente uma intervenção completa de mecânica, incluindo cabeça de motor nova, ficando assim totalmente revista e pronta para muitos quilómetros com..."
    }
  ]
};

export function getMockDeals(zone) {
  if (zone === "all") {
    return [...MOCK_DEALS.norte, ...MOCK_DEALS.centro, ...MOCK_DEALS.sul];
  }
  return MOCK_DEALS[zone] || [];
}
